---
title: 3D-kever
hero_image: images/banner.png
description: Ontwerp een 3D-printbare kever met BlocksCAD
version: 1
listed: true
copyedit: true
last_tested: "2019-03-21"
steps:
  - title: Inleiding
  - title: Geef je kever een lichaam
  - title: Maak de basis van het lichaam plat
  - title: Voeg een kop toe aan je kever
  - title: Maak benen
  - title: "Uitdaging: ontwerp je eigen kever"
  - title: 3D print en versier je ontwerp
