title: blockscad-bug
hero_image: images/banner.png
description: Design a 3D printable bug (insect) with BlocksCAD.
version: 1
listed: false
copyedit: false
last_tested: "2019-03-13"
steps:
  - title: Introduction
  - title: Give the bug a body
  - title: Flatten the body
  - title: Add a head
  - title: Legs
  - title: Design your own bug
  - title: 3D printing and decoration
