---
title: Bug 3D
hero_image: images/banner.png
description: Cria um inseto para impressão em 3D com o BlocksCAD
version: 1
listed: true
copyedit: true
last_tested: "2019-03-21"
steps:
  - 
    title: Introdução
  - 
    title: Dá um corpo ao teu bug
  - 
    title: Achata a base do corpo
  - 
    title: Acrescenta uma cabeça ao teu inseto
  - 
    title: Criar pernas
  - 
    title: Cria o teu próprio inseto
  - 
    title: Imprime em 3D e decora o teu inseto
