---
title: 3D昆虫
hero_image: images/banner.png
description: 使用BlocksCAD设计3D打印的昆虫
version: 1
listed: true
copyedit: true
last_tested: "2019-03-21"
steps:
  - 
    title: 介绍
  - 
    title: 给你的虫子一个身体
  - 
    title: 展平身体
  - 
    title: 为您的昆虫添加头
  - 
    title: 创建腿
  - 
    title: "Challenge: Design your own bug"
    challenge: true
  - 
    title: 3D打印和装饰您的设计
