---
title: 3D bug
hero_image: images/banner.png
description: Dizajnirajte 3D bug insekta s BlocksCAD-om
version: 1
listed: true
copyedit: true
last_tested: '2019-03-21'
steps:
  - 
    title: Sretan rođendan
  - 
    title: Dajte tijelu svoju bubu
  - 
    title: Izravnajte bazu tijela
    completion:
      - engaged
  - 
    title: Dodajte glavu svom bugu
  - 
    title: Stvorite noge
    completion:
      - internal
  - 
    title: 'Challenge: Design your own bug'
    challenge: true
  - 
    title: 3D ispis i ukrašavanje vašeg dizajna
