---
title: Byg 3D
hero_image: images/banner.png
description: Dyluniwch bryfyn byg 3D-argraffadwy gyda BlocksCAD
version: 1
listed: true
copyedit: true
last_tested: "2019-03-21"
steps:
  - 
    title: Cyflwyniad
  - 
    title: Rhowch gorff i'ch byg
  - 
    title: Fflatiwch waelod y corff
  - 
    title: Ychwanegwch ben at eich nam
  - 
    title: Creu coesau
  - 
    title: Dyluniwch eich nam eich hun
  - 
    title: Argraffu 3D ac addurno'ch dyluniad
