---
title: 3D Käfer
hero_image: images/banner.png
description: Entwerfe mit BlocksCAD ein 3D-druckbares Insekt
version: 1
listed: true
copyedit: true
last_tested: '2019-03-21'
steps:
- title: Einleitung
- title: Gib deinem Käfer einen Körper
- title: Die Basis des Körpers abflachen
  completion:
  - engaged
- title: Füge deinem Käfer einen Kopf hinzu
- title: Erstelle Beine
  completion:
  - internal
- title: Entwerfe deinen eigenen Käfer
- title: 3D drucke und dekoriere dein Design
