---
title: Bug 3D
hero_image: images/banner.png
description: Proiectați o insectă cu bug imprimabilă 3D cu BlocksCAD
version: 1
listed: true
copyedit: true
last_tested: "2019-03-21"
steps:
  - 
    title: Introducere
  - 
    title: Dă-ți un corp de eroare
  - 
    title: Aplatizați baza corpului
  - 
    title: Adăugați un cap la eroare
  - 
    title: Creați picioare
  - 
    title: Proiectați-vă propriul bug
  - 
    title: Imprimare 3D și decorați designul
