---
title: Insectă 3D
hero_image: images/banner.png
description: Proiectează o insectă 3D cu BlocksCAD
version: 1
listed: true
copyedit: true
last_tested: '2019-03-21'
steps:
- title: Introducere
- title: Dă-i insectei un corp
- title: Aplatizează baza corpului
  completion:
  - engaged
- title: Adaugă un cap la insecta ta
- title: Creează-i picioarele
  completion:
  - internal
- title: 'Provocare: proiectează-ți propria insectă'
- title: Imprimă 3D și personalizează-ți design-ul tău
