---
title: Bug 3D
hero_image: images/banner.png
description: Crie um inseto para impressão em 3D com o BlocksCAD
version: 1
listed: true
copyedit: true
last_tested: "2019-03-21"
steps:
  - 
    title: Introdução
  - 
    title: Dê um corpo ao seu bug
  - 
    title: Achatar a base do corpo
  - 
    title: Adicione uma cabeça ao seu bug
  - 
    title: Criar pernas
  - 
    title: "Crie seu próprio inseto"
    challenge: true
  - 
    title: Imprima em 3D e decore seu design
