---
title: 3D chyba
hero_image: images/banner.png
description: Navrhněte hmyzí hmyz s možností tisku 3D pomocí BlocksCAD
version: 1
listed: true
copyedit: true
last_tested: "2019-03-21"
steps:
  - 
    title: Úvod
  - 
    title: Dejte své chybě tělo
  - 
    title: Srovnejte spodní část těla
  - 
    title: Přidejte ke své chybě hlavu
  - 
    title: Vytvořte nohy
  - 
    title: Navrhněte si vlastní chybu
  - 
    title: 3D tisk a ozdobte svůj design
