---
title: Insecto en 3D
hero_image: images/banner.png
description: Diseña un insecto imprimible en 3D con BlocksCAD
version: 1
listed: true
copyedit: true
last_tested: "2019-03-21"
steps:
  - 
    title: Introducción
  - 
    title: Dale cuerpo a tu insecto
  - 
    title: Aplana la base del cuerpo
  - 
    title: Añade la cabeza a tu insecto
  - 
    title: Crea las patas
  - 
    title: Diseña tu propio insecto
  - 
    title: Imprime en 3D y decora tu diseño
