---
title: 3D chyba
hero_image: images/banner.png
description: Navrhnite hmyz s 3D potlačiteľnou chybou s programom BlocksCAD
version: 1
listed: true
copyedit: true
last_tested: "2019-03-21"
steps:
  - 
    title: Úvod
  - 
    title: Dajte svojmu telu chybu
  - 
    title: Zrovnajte spodnú časť tela
  - 
    title: Pridajte hlavu k svojej chybe
  - 
    title: Vytvorte nohy
  - 
    title: Navrhnite si svoju vlastnú chybu
  - 
    title: 3D tlač a ozdobte svoj dizajn
