---
title: Insecte 3D
hero_image: images/banner.png
description: Concevoir un insecte imprimable en 3D avec BlocksCAD
version: 1
listed: true
copyedit: true
last_tested: '2019-03-21'
steps:
- title: Introduction
  completion: engaged
- title: Donne un corps à ton insecte
- title: Aplatir la base du corps
- title: Ajoute une tête à ton insecte
- title: Créer des pattes
- title: Concevoir ton propre insecte
  challenge: true
  completion: internal
- title: Imprime en 3D et décore ton design
