---
title: 3D hata
hero_image: images/banner.png
description: BlocksCAD ile 3D yazdırılabilir böcek böcekleri tasarlayın
version: 1
listed: true
copyedit: true
last_tested: "2019-03-21"
steps:
  - 
    title: Giriş
  - 
    title: Böceğinize bir beden verin
  - 
    title: Vücudun tabanını düzleştirin
  - 
    title: Hatanıza bir kafa ekleyin
  - 
    title: Bacak oluştur
  - 
    title: Kendi hatanızı tasarlayın
  - 
    title: 3D baskı ve tasarımınızı süsleyin
