---
title: 3D Böcek
hero_image: images/banner.png
description: BlocksCAD ile 3D yazdırılabilir böcekler tasarlayın
version: 1
listed: true
copyedit: true
last_tested: "2019-03-21"
steps:
  - 
    title: Giriş
  - 
    title: Böceğinize bir beden verin
  - 
    title: Vücudun tabanını düzleştirin
  - 
    title: Böceğinize bir kafa ekleyin
  - 
    title: Bacak oluşturun
  - 
    title: Kendi böceğinizi tasarlayın
  - 
    title: 3D baskı ve tasarımınızı süsleyin
